services:
  - type: web
    name: pdf-nutrition-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: gemini
      - key: PYTHON_VERSION
        value: 3.13.0
